project:
  title: "`foil` ISC proposal"
  render:
    - "*.qmd"
    - "!proposal/"

date: today
date-format: iso
format:
  html:
    embed-resources: true
  hikmah-pdf:
    geometry:
      - left=1.25in
      - right=1.25in
bibliography: references.bib
number-sections: true

author:
  - name: Visruth Srimath Kandali
    orcid: 0009-0005-9097-0688
    affiliations:
      - "California Polytechnic State University, San Luis Obispo"
